#!/usr/bin/perl
#
# script for building CLIPS program from Protoge export
# saves output to "$OUT_FILE"
# @author deric 
$CLIPS_FILE="clips.clp";
$OUT_FILE="housing.clp";

open OUT, ">$OUT_FILE" or die $!;
 my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime time;
 $year=$year+1900;
print OUT ";; Builded on  $year-$mon-$mday $hour:$min:$sec \n";



print OUT "\n;############### ontology ##################\n";
$pont="export/housing.pont";
open(FILE, $pont) || die("Could not open file $pont!");
while (<FILE>) {
  print OUT $_;
  $i++;
}
close FILE;
print OUT "\n\n
;############### instances ##################
(definstances inst \n";

$inst="export/instances.pins";
open(FILE, $inst) || die("Could not open file $inst!");
while (<FILE>) {
  print OUT $_;
  $i++;
}
close FILE;
print OUT ")";


print OUT ";;############### program ##################\n";

open(FILE, $CLIPS_FILE) || die("Could not open file $CLIPS_FILE!");
@i=0;
while (<FILE>) {
  print OUT $_;
  $i++;
}
close FILE;


close OUT;

print "housing build completed. $i lines\n";
